services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  s3:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
    command: server /data

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - video-service
    volumes:
      - ./utils:/app/utils
      - ./common:/app/common
      - ./config:/app/config

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - postgres
    volumes:
      - ./utils:/app/utils
      - ./common:/app/common
      - ./config:/app/config

  video-service:
    build: ./video-service
    ports:
      - "8082:8082"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - postgres
      - s3
    volumes:
      - ./utils:/app/utils
      - ./common:/app/common
      - ./config:/app/config

# Optional volume definitions (if you need to persist the data or reuse them across containers)
# volumes:
#   postgres_data:
#   s3_data:
